"""LLM auditor orchestration.

The auditor writes prose grounded in findings the deterministic layers already
produced. It never sets or moves a score. When every provider fails, the
deterministic output stands alone and the report says so.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from core.config import RuntimeConfig
from core.layer3.provenance import enforce_word_budget

logger = logging.getLogger(__name__)

_PROMPT_PATH = Path(__file__).resolve().parents[2] / "prompts" / "auditor_v2.txt"

UNAVAILABLE_NOTE = (
    "LLM auditor unavailable; the deterministic findings above stand alone."
)


def _read_system_prompt() -> str:
    with open(_PROMPT_PATH, encoding="utf-8") as f:
        return f.read()


def _build_provider(name: str, cfg: RuntimeConfig) -> Any:
    if name == "anthropic" and cfg.anthropic_key:
        from core.providers.anthropic_provider import AnthropicProvider

        return AnthropicProvider(cfg.anthropic_key)
    if name == "openai" and cfg.openai_key:
        from core.providers.openai_provider import OpenAIProvider

        return OpenAIProvider(cfg.openai_key)
    if name == "gemini" and cfg.google_key:
        from core.providers.gemini_provider import GeminiProvider

        return GeminiProvider(cfg.google_key)
    return None


def run_audit(
    text: str,
    deterministic_findings: dict[str, Any],
    cfg: RuntimeConfig,
    providers: list[str],
    word_budget: int | None = None,
) -> dict[str, Any]:
    """Returns the llm_audit report section. Deterministic scores are inputs, never outputs."""
    if not providers:
        return {"available": False, "note": UNAVAILABLE_NOTE}
    system_prompt = _read_system_prompt()
    for name in providers:
        provider = _build_provider(name, cfg)
        if provider is None:
            continue
        model = cfg.models.get(name, "")
        try:
            artifacts = provider.audit(
                text, deterministic_findings, system_prompt, model, timeout=cfg.timeout_sec
            )
        except Exception as exc:  # noqa: BLE001 - any provider failure falls through
            logger.warning("provider %s failed: %s", name, exc)
            continue
        review = artifacts["critical_review"]
        research = artifacts["proposed_research"]
        if word_budget is not None:
            review, _ = enforce_word_budget(review, word_budget)
            research, _ = enforce_word_budget(research, word_budget)
        return {
            "available": True,
            "provider": name,
            "model_version": model,
            "critical_review": review,
            "proposed_research": research,
            "note": f"artifacts generated by {name}:{model}; deterministic scores unaffected",
        }
    return {"available": False, "note": UNAVAILABLE_NOTE}
